plugins {
    id 'com.android.application'
}

android {
    namespace 'org.genesisai.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'org.genesisai.mobile'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '0.1.0-alpha.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
