from __future__ import annotations

import json
import os
from pathlib import Path
import urllib.error
import urllib.request

from genesis_hourly_ops import render_email


ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ROOT / "runtime"
MARKER = "<!-- genesis-hourly-report:v1 -->"


def request(method: str, path: str, payload: dict | None = None):
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    if not token or not repo:
        raise RuntimeError("GITHUB_TOKEN and GITHUB_REPOSITORY are required")
    data = None if payload is None else json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"https://api.github.com/repos/{repo}{path}",
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
            "User-Agent": "Genesis-AI-Network",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as response:
            body = response.read().decode("utf-8")
            return json.loads(body) if body else {}
    except urllib.error.HTTPError as exc:
        raise RuntimeError(f"GitHub report HTTP {exc.code}: {exc.read().decode('utf-8', errors='replace')[:500]}") from exc


def ensure_report_issue() -> dict:
    issues = request("GET", "/issues?state=all&per_page=100")
    for issue in issues:
        if "pull_request" not in issue and MARKER in str(issue.get("body") or ""):
            if issue.get("state") == "closed":
                return request("PATCH", f"/issues/{issue['number']}", {"state": "open"})
            return issue
    return request("POST", "/issues", {
        "title": "[Genesis Hourly Report] Operations and KPI dashboard",
        "body": (
            f"{MARKER}\n"
            "Persistent GitHub-native reporting channel for Genesis. Genesis posts one scheduled hourly operations/KPI report here. "
            "GitHub notifications are the primary delivery mechanism; SMTP is optional.\n\n"
            "@Maxhm007 subscribe to this issue or keep GitHub email notifications enabled to receive each report by email."
        ),
    })


def main() -> None:
    issue = ensure_report_issue()
    subject, body = render_email()
    comment = (
        "@Maxhm007\n\n"
        f"## {subject}\n\n"
        "```text\n"
        f"{body.rstrip()}\n"
        "```\n\n"
        "This report was generated by Genesis on the GitHub runner. Operational issues are persisted and routed through the Automation Module."
    )
    posted = request("POST", f"/issues/{issue['number']}/comments", {"body": comment})
    result = {
        "status": "posted",
        "issue_number": issue.get("number"),
        "comment_id": posted.get("id"),
        "subject": subject,
    }
    RUNTIME.mkdir(parents=True, exist_ok=True)
    (RUNTIME / "github_hourly_report_status.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(result, sort_keys=True))


if __name__ == "__main__":
    main()
