from pathlib import Path

path = Path("genesis/benchmark_execution.py")
text = path.read_text(encoding="utf-8")

anchor = '''    @classmethod\n    def _execution_readiness(cls, benchmark_id: str) -> dict[str, Any]:\n'''
method = '''    @classmethod\n    def _working_memory(\n        cls,\n        benchmark_id: str,\n        latest: GenesisTask | None,\n        readiness: dict[str, Any],\n    ) -> dict[str, Any]:\n        \"\"\"Keep the benchmark lane focused on current progress and localized evidence.\"\"\"\n        generation = cls._runner_generation(latest) if latest is not None else 0\n        state = latest.state if latest is not None else \"not_started\"\n        last_failure = \"\"\n        if latest is not None:\n            last_failure = str(latest.last_error or \"\").strip()\n            if not last_failure and latest.failure_history:\n                last_failure = str(latest.failure_history[-1].get(\"error\") or \"\").strip()\n        missing = tuple(str(item) for item in readiness.get(\"missing\", [])[:16])\n        exhausted = generation >= cls.MAX_RUNNER_INTEGRATION_GENERATIONS and latest is not None\n        if exhausted and benchmark_id not in cls.EVIDENCE_ADAPTER_BENCHMARKS:\n            selected_skill = \"engineering_assistance\"\n        elif exhausted and not bool(readiness.get(\"ready\")):\n            selected_skill = \"external_execution_readiness\"\n        elif exhausted:\n            selected_skill = \"benchmark_evidence_staging\"\n        else:\n            selected_skill = \"benchmark_runner_integration\"\n        return {\n            \"benchmark_id\": benchmark_id,\n            \"runner_generation\": generation,\n            \"runner_state\": state,\n            \"last_failure\": last_failure[:500],\n            \"missing_prerequisites\": missing,\n            \"selected_skill\": selected_skill,\n            \"strategy_change_required\": generation > 0,\n        }\n\n'''
if text.count(anchor) != 1:
    raise SystemExit("working-memory insertion anchor mismatch")
text = text.replace(anchor, method + anchor, 1)

old = '''        existing = self._runner_tasks(benchmark_id)\n        latest = max(existing, key=self._runner_generation) if existing else None\n        if latest is not None and latest.state not in self.TERMINAL_RUNNER_STATES:\n            return {\n                \"status\": \"runner_work_queued\",\n                \"benchmark_id\": benchmark_id,\n                \"task_id\": latest.task_id,\n                \"created\": False,\n                \"work_generation\": self._runner_generation(latest),\n                \"runner_state\": latest.state,\n            }\n\n        readiness = self._execution_readiness(benchmark_id)\n'''
new = '''        existing = self._runner_tasks(benchmark_id)\n        latest = max(existing, key=self._runner_generation) if existing else None\n        readiness = self._execution_readiness(benchmark_id)\n        working_memory = self._working_memory(benchmark_id, latest, readiness)\n        if latest is not None and latest.state not in self.TERMINAL_RUNNER_STATES:\n            return {\n                \"status\": \"runner_work_queued\",\n                \"benchmark_id\": benchmark_id,\n                \"task_id\": latest.task_id,\n                \"created\": False,\n                \"work_generation\": self._runner_generation(latest),\n                \"runner_state\": latest.state,\n                \"working_memory\": working_memory,\n            }\n\n'''
if text.count(old) != 1:
    raise SystemExit("runner-task readiness anchor mismatch")
text = text.replace(old, new, 1)

text = text.replace('''                    \"engineering_assistance_required\": True,\n                    \"owner_action_required\": False,\n                }\n''', '''                    \"engineering_assistance_required\": True,\n                    \"owner_action_required\": False,\n                    \"working_memory\": working_memory,\n                }\n''', 1)
text = text.replace('''                    \"last_work_generation\": self._runner_generation(latest),\n                    \"owner_action_required\": True,\n                }\n''', '''                    \"last_work_generation\": self._runner_generation(latest),\n                    \"owner_action_required\": True,\n                    \"working_memory\": working_memory,\n                }\n''', 1)

old = '''        if generation > 1:\n            objective += (\n                f\" This is integration generation {generation}. Do not repeat the previous implementation approach; \"\n                \"use different repository evidence, adapter boundaries, or execution strategy while preserving all validation rules.\"\n            )\n            if prior_failure:\n                objective += f\" Previous bounded attempt ended with: {prior_failure[:500]}\"\n'''
new = '''        if generation > 1:\n            objective += (\n                f\" This is integration generation {generation}. Do not repeat the previous implementation approach; \"\n                \"use different repository evidence, adapter boundaries, or execution strategy while preserving all validation rules.\"\n            )\n            if prior_failure:\n                objective += f\" Previous bounded attempt ended with: {prior_failure[:500]}\"\n        objective += f\" Current bounded working memory: {json.dumps(working_memory, sort_keys=True)}\"\n'''
if text.count(old) != 1:
    raise SystemExit("objective working-memory anchor mismatch")
text = text.replace(old, new, 1)

old = '''                \"work_generation\": generation,\n                \"strategy_change_required\": generation > 1,\n            },\n'''
new = '''                \"work_generation\": generation,\n                \"strategy_change_required\": generation > 1,\n                \"working_memory\": working_memory,\n            },\n'''
if text.count(old) != 1:
    raise SystemExit("payload working-memory anchor mismatch")
text = text.replace(old, new, 1)

old = '''            \"work_generation\": generation,\n            \"runner_state\": child.state,\n        }\n'''
new = '''            \"work_generation\": generation,\n            \"runner_state\": child.state,\n            \"working_memory\": working_memory,\n        }\n'''
if text.count(old) != 1:
    raise SystemExit("result working-memory anchor mismatch")
text = text.replace(old, new, 1)
path.write_text(text, encoding="utf-8")


tests = Path("tests/test_benchmark_execution.py")
test_text = tests.read_text(encoding="utf-8")
append = '''\n\ndef test_runner_task_carries_bounded_working_memory_snapshot(tmp_path: Path) -> None:\n    task = make_task(tmp_path, \"new_frontier_benchmark\")\n    planner = BenchmarkExecutionPlanner(tmp_path)\n    result = planner.advance(task)\n    memory = result[\"working_memory\"]\n    assert memory[\"runner_generation\"] == 0\n    assert memory[\"runner_state\"] == \"not_started\"\n    assert memory[\"selected_skill\"] == \"benchmark_runner_integration\"\n    child = planner.queue.get(result[\"task_id\"])\n    assert child is not None\n    assert child.payload[\"working_memory\"] == memory\n    assert \"Current bounded working memory:\" in child.objective\n\n\ndef test_exhausted_unknown_runner_localizes_next_skill_to_engineering_assistance(tmp_path: Path) -> None:\n    task = make_task(tmp_path, \"new_frontier_benchmark\")\n    planner = BenchmarkExecutionPlanner(tmp_path)\n    for _ in range(planner.MAX_RUNNER_INTEGRATION_GENERATIONS):\n        attempt = planner.advance(task)\n        child = planner.queue.get(attempt[\"task_id\"])\n        assert child is not None\n        planner.queue.transition(child.task_id, \"assigned\", module_id=\"genesis.coding\")\n        planner.queue.transition(child.task_id, \"running\", module_id=\"genesis.coding\")\n        planner.queue.transition(child.task_id, \"failed\", module_id=\"genesis.coding\", error=\"localized runner failure\")\n        planner.queue.transition(child.task_id, \"quarantined\", module_id=\"genesis.coding\")\n    result = planner.advance(task)\n    memory = result[\"working_memory\"]\n    assert memory[\"selected_skill\"] == \"engineering_assistance\"\n    assert memory[\"last_failure\"] == \"localized runner failure\"\n    assert memory[\"runner_generation\"] == planner.MAX_RUNNER_INTEGRATION_GENERATIONS\n\n\ndef test_terminal_readiness_working_memory_localizes_missing_prerequisites(tmp_path: Path, monkeypatch) -> None:\n    for name in BenchmarkExecutionPlanner.TERMINAL_BENCH_ENV:\n        monkeypatch.delenv(name, raising=False)\n    monkeypatch.setattr(\"genesis.benchmark_execution.shutil.which\", lambda _: None)\n    task = make_task(tmp_path)\n    planner = BenchmarkExecutionPlanner(tmp_path)\n    for _ in range(planner.MAX_RUNNER_INTEGRATION_GENERATIONS):\n        attempt = planner.advance(task)\n        quarantine(planner.queue, attempt[\"task_id\"])\n    result = planner.advance(task)\n    memory = result[\"working_memory\"]\n    assert memory[\"selected_skill\"] == \"external_execution_readiness\"\n    assert \"harbor_cli\" in memory[\"missing_prerequisites\"]\n    assert \"GENESIS_BENCHMARK_MODEL\" in memory[\"missing_prerequisites\"]\n'''
if "test_runner_task_carries_bounded_working_memory_snapshot" not in test_text:
    tests.write_text(test_text.rstrip() + append + "\n", encoding="utf-8")
